language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marko1212/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marko1212/react-test npm run test

after_success:
  - docker build -t marko1212/multi-client ./client
  - docker build -t marko1212/multi-nginx ./nginx
  - docker build -t marko1212/multi-server ./server
  - docker build -t marko1212/multi-worker ./worker
